name = "petme-frontend"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
pages_build_output_dir = ".open-next/assets"

[assets]
directory = ".open-next/assets"
binding = "OPENNEXT_ASSETS"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "petme-next-cache"

[vars]
API_BASE_URL = "{{ env.API_BASE_URL }}"
NEXT_PUBLIC_API_BASE_URL = "{{ env.NEXT_PUBLIC_API_BASE_URL }}"
